### ISSUE TITLE
User facing docs

### ISSUE THREAD

**Issue by kenpaicat** [SloveniaEngineering/laguna-docs#1]
Tracked by: https://github.com/SloveniaEngineering/laguna-backend/issues/53
* User facing docs so v posebnem repozitoriju (temu)
* Lahko izbereta poljubne tehnologije in jezike za generacijo dokumentacije
* Gre za splošno dokumentacijo uporabniku oz. adminu oz. moderatorju. Za morebitne API userje jih napotimo na https://sloveniaengineering.github.io/laguna-backend.

**Comment by Skrivni** [comment]
Hm ok upam da nism kaj zafukal.
User-facing docs bi predlagal slovenjenje v "Uporabniško orientirana dokumentacija". 
**Uporabniško orientirana dokumentacija**
*Dokumentacija vsebuje navodila za uporabo splošnim uporabnikom spletne strani in tako zajema uporabnike, administratorje in moderatorje. Potencialni API uporabniki se prosim obrnite na API dokumentacijo [link]

**Comment by kenpaicat** [comment]
Priporočam da si prvo izbereta enega od naslednjih orodij za lepo dokumentacijo: https://docusaurus.io/docs#comparison-with-other-tools ali pa kar docusaurus.

Potem pa tam začneta pisati uvod.

Lp
ken

**Comment by kenpaicat** [comment]
Closed due to stale.
